using Microsoft.EntityFrameworkCore.Migrations;

namespace LTCSDL.DAL.Migrations
{
    public partial class i : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Chapters",
                columns: table => new
                {
                    ChapterId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(maxLength: 200, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Chapters", x => x.ChapterId);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    UserId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FullName = table.Column<string>(maxLength: 200, nullable: false),
                    UserName = table.Column<string>(maxLength: 200, nullable: false),
                    Password = table.Column<string>(maxLength: 20, nullable: false),
                    Email = table.Column<string>(maxLength: 200, nullable: false),
                    Job = table.Column<string>(maxLength: 200, nullable: false),
                    TypeUser = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.UserId);
                });

            migrationBuilder.CreateTable(
                name: "Groups",
                columns: table => new
                {
                    GroupId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(maxLength: 200, nullable: false),
                    ChapterId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Groups", x => x.GroupId);
                    table.ForeignKey(
                        name: "FK_Groups_Chapters_ChapterId",
                        column: x => x.ChapterId,
                        principalTable: "Chapters",
                        principalColumn: "ChapterId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Numbers",
                columns: table => new
                {
                    NumberId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(maxLength: 200, nullable: false),
                    GroupId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Numbers", x => x.NumberId);
                    table.ForeignKey(
                        name: "FK_Numbers_Groups_GroupId",
                        column: x => x.GroupId,
                        principalTable: "Groups",
                        principalColumn: "GroupId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Diseases",
                columns: table => new
                {
                    DiseaseId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    EnglishName = table.Column<string>(maxLength: 200, nullable: false),
                    VietnameseName = table.Column<string>(maxLength: 200, nullable: false),
                    Symptom = table.Column<string>(nullable: false),
                    NumberId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Diseases", x => x.DiseaseId);
                    table.ForeignKey(
                        name: "FK_Diseases_Numbers_NumberId",
                        column: x => x.NumberId,
                        principalTable: "Numbers",
                        principalColumn: "NumberId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Diseases_Users",
                columns: table => new
                {
                    DiseaseId = table.Column<int>(nullable: false),
                    UserId = table.Column<int>(nullable: false),
                    Saved = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Diseases_Users", x => new { x.DiseaseId, x.UserId });
                    table.ForeignKey(
                        name: "FK_Diseases_Users_Diseases_DiseaseId",
                        column: x => x.DiseaseId,
                        principalTable: "Diseases",
                        principalColumn: "DiseaseId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Diseases_Users_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "UserId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Name" },
                values: new object[,]
                {
                    { 1, "Bệnh nhiễm trùng và ký sinh trùng" },
                    { 20, "Các nguyên nhân ngoại sinh của bệnh và tử vong" },
                    { 19, "Vết thương ngộ độc và hậu quả của 1 số nguyên nhân bên ngoài" },
                    { 18, "Các triệu chứng, dấu hiệu và những biển hiện lâm sàng, cận lâm sàng bất thường, chưa được phân loại ở phần khác" },
                    { 17, "Dị tật bẩm sinh, biến dạng và bất thường về nhiễm sắc thể" },
                    { 16, "Một số bệnh lý xuất phát trong thời kỳ chu sinh" },
                    { 15, "Thai nghén, sinh đẻ và hậu sản" },
                    { 14, "Bệnh hệ sinh dục – Tiết niệu" },
                    { 13, "Bệnh của hệ cơ – xương khớp và mô liên kết" },
                    { 12, "Nhiễm trùng da và tổ chức dưới da" },
                    { 11, "Bệnh hệ tiêu hoá" },
                    { 10, "Bệnh Hô hấp" },
                    { 9, "Bệnh hệ tuần hoàn" },
                    { 8, "Bệnh của tai và xương chũm" },
                    { 7, "Bệnh mắt và phần phụ" },
                    { 6, "Bệnh hệ thần kinh" },
                    { 5, "Rối loạn tâm thần và hành vi" },
                    { 4, "Bệnh nội tiết, dinh dưỡng và chuyển hóa" },
                    { 3, "Bệnh của máu, cơ quan tạo máu và các rối loạn liên quan đến cơ chế miễn dịch" },
                    { 2, "U (U tân sinh)" },
                    { 21, "Các yếu tố ảnh hưởng đến tình trạng sức khỏe và tiếp xúc dịch vụ y tế" },
                    { 22, "Mã phục vụ những mục đích đặc biệt" }
                });

            migrationBuilder.InsertData(
                table: "Groups",
                columns: new[] { "GroupId", "ChapterId", "Name" },
                values: new object[,]
                {
                    { 7, 1, "Viêm gan virus" },
                    { 138, 15, "Thai nghén và sẩy thai" },
                    { 139, 15, "Biến chứng chủ yếu liên quan đến sau đẻ" },
                    { 140, 15, "Các tình trạng sản khoa khác, chưa được phân loại ở phần khác (O94-O99)" },
                    { 141, 16, "Thai nhi và trẻ sơ sinh bị ảnh hưởng do các yếu tố về phía mẹ và bởi các biến chứng của thời kỳ thai nghén, chuyển dạ và cuộc đẻ" },
                    { 142, 16, "Các rối loạn nội tiết, chuyển hóa tạm thời đặc hiệu cho thai và trẻ sơ sinh" },
                    { 143, 16, "Rối loạn chảy máu và huyết học của thai và trẻ sơ sinh" },
                    { 144, 16, "Chấn thương khi sinh" },
                    { 145, 16, "Rối loạn hô hấp và tim mạch đặc hiệu cho giai đoạn chu sinh" },
                    { 146, 16, "Nhiễm khuẩn đặc hiệu trong thời kỳ chu sinh" },
                    { 147, 16, "Các bệnh lý của da và điều hòa thân nhiệt của thai và trẻ sơ sinh" },
                    { 148, 16, "Các rối loạn của hệ thống tiêu hóa ở thai và trẻ sơ sinh" },
                    { 149, 16, "Các rối loạn liên quan đến tuổi thai và sự phát triển của thai" },
                    { 150, 16, "Các bệnh lý khác xuất phát từ giai đoạn chu sinh" },
                    { 151, 17, "Dị tật và biến dạng bẩm sinh của hệ cơ xương" },
                    { 152, 17, "Các dị tật bẩm sinh khác của hệ tiêu hoá" },
                    { 153, 17, "Dị tật bẩm sinh của cơ quan sinh dục" },
                    { 154, 17, "Các dị tật bẩm sinh của hệ tiết niệu" },
                    { 155, 17, "Các dị tật bẩm sinh của hệ thống tuần hoàn" },
                    { 156, 17, "Khe hở môi và khe hở vòm miệng" },
                    { 157, 17, "Các dị tật bẩm sinh khác" },
                    { 158, 17, "Dị tật bẩm sinh hệ thần kinh trung ương" },
                    { 137, 15, "Các bệnh lý khác của bà mẹ chủ yếu liên quan đến thai nghén" },
                    { 136, 15, "Chăm sóc bà mẹ liên quan đến thai, buồng ối và có thể là các vấn đề khi đẻ" },
                    { 135, 15, "Phù, protein niệu và tăng huyết áp trong khi có thai, khi đẻ và sau đẻ" },
                    { 134, 15, "Cuộc đẻ" },
                    { 112, 12, "Viêm da và chàm" },
                    { 113, 12, "Mày đay và hồng ban" },
                    { 114, 12, "Các bệnh phần phụ của da" },
                    { 115, 12, "Bệnh sẩn có vảy" },
                    { 116, 13, "Bệnh của xương và sụn" },
                    { 117, 13, "Bệnh khớp" },
                    { 118, 13, "Bệnh cột sống" },
                    { 119, 13, "Các bệnh khác của hệ cơ - xương - khớp và mô liên kết" },
                    { 120, 13, "Bệnh mô liên kết hệ thống" },
                    { 121, 13, "Các bệnh lý mô mềm" },
                    { 159, 17, "Các bất thường nhiễm sắc thể, chưa được phân loại" },
                    { 122, 14, "Bệnh cầu thận" },
                    { 124, 14, "Các rối loạn khác của hệ sinh dục tiết niệu" },
                    { 125, 14, "Biến đổi không do viêm của đường sinh dục nữ" },
                    { 126, 14, "Bệnh cơ quan sinh dục nam" },
                    { 127, 14, "Các bệnh khác của hệ tiết niệu" },
                    { 128, 14, "Bệnh kẽ ống thận" },
                    { 129, 14, "Suy thận" },
                    { 130, 14, "Các rối loạn khác của thận và niệu quản" },
                    { 131, 14, "Các biến đổi của vú" },
                    { 132, 14, "Viêm cơ quan sinh dục vùng chậu nữ" },
                    { 133, 15, "Biến chứng của chuyển dạ và đẻ" },
                    { 123, 14, "Sỏi tiết niệu" },
                    { 160, 17, "Các dị tật bẩm sinh ở mắt, tai, mặt và cổ" },
                    { 161, 17, "Các bất thường bẩm sinh của bộ máy hô hấp" },
                    { 162, 18, "Triệu chứng và dấu hiệu liên quan tới hệ tiêu hoá và bụng" },
                    { 189, 19, "Tổn thương tại đầu gối và cẳng chân" },
                    { 190, 19, "Tổn thương do cóng lạnh" },
                    { 191, 19, "Tổn thương ở đầu" },
                    { 192, 19, "Tổn thương của cổ" },
                    { 193, 19, "Vết thương vai và cánh tay" },
                    { 194, 19, "Ngộ độc chất chủ yếu không có nguồn gốc y học" },
                    { 195, 19, "Tác dụng khác và chưa xác định của căn nguyên bên ngoài" },
                    { 196, 20, "Can thiệp pháp lý và hành động chiến tranh" },
                    { 197, 20, "Di chứng của các nguyên nhân bên ngoài gây biến chứng và tử vong" },
                    { 198, 20, "Tai nạn" },
                    { 188, 19, "Tổn thương lồng ngực" },
                    { 199, 20, "Tấn công" },
                    { 201, 20, "Biến cố do ý đồ không xác định được." },
                    { 202, 20, "Các yếu tố bổ sung liên quan đến các nguyên nhân gây ra biến chứng và tử vong được sắp xếp ở nơi khác" },
                    { 203, 20, "Cố tình tự hại" },
                    { 204, 21, "Những người có nguy cơ sức khoẻ tiềm ẩn liên quan đến bệnh sử gia đình và cá nhân và một số tình trạng ảnh hưởng đến sức khoẻ" },
                    { 205, 21, "Những người có nguy cơ sức khoẻ tiềm tàng liên quan đến những hoàn cảnh kinh tế xã hội và tâm lý xã hội" },
                    { 206, 21, "Người bệnh đến cơ sở y tế trong các hoàn cảnh khác" },
                    { 207, 21, "Những người có nguy cơ tiềm tàng về sức khoẻ liên quan đến các bệnh lây truyền" },
                    { 208, 21, "Những người đến cơ quan y tế về các vấn đề liên quan đến sinh sản" },
                    { 209, 21, "Những người đến cơ sở y tế để khám và kiểm tra sức khoẻ" },
                    { 210, 21, "Những người đến cơ sở y tế để được chăm sóc và tiến hành các thủ thuật đặc biệt" },
                    { 200, 20, "Biến chứng do chăm sóc y tế và phẫu thuật" },
                    { 111, 12, "Bệnh da bọng nước" },
                    { 187, 19, "Biến chứng phẫu thuật và chăm sóc y tế không xếp loại ở nơi khác" },
                    { 185, 19, "Tổn thương phần chưa xác định của thân, các chi hoặc vùng cơ thể" },
                    { 163, 18, "Triệu chứng và dấu hiệu tổng quát" },
                    { 164, 18, "Triệu chứng và dấu hiệu liên quan tới hệ tuần hoàn và hô hấp" },
                    { 165, 18, "Triệu chứng và dấu hiệu liên quan tới ngôn ngữ và giọng nói" },
                    { 166, 18, "Triệu chứng và dấu hiệu liên quan tới nhận thức, tri giác và trạng thái cảm" },
                    { 167, 18, "Phát hiện bất thường về xét nghiệm máu, không có chẩn đoán" },
                    { 168, 18, "Triệu chứng và dấu hiệu liên quan tới hệ thần kinh và hệ cơ xương" },
                    { 169, 18, "Các phát hiện bất thường về xét nghiệm nước tiểu, không có chẩn đoán" },
                    { 170, 18, "Các phát hiện bất thường về chẩn đoán hình ảnh và thăm dò chức năng, không có chẩn đoán" },
                    { 171, 18, "Triệu chứng và dấu hiệu liên quan tới da và tổ chức dưới da" },
                    { 172, 18, "Nguyên nhân tử vong không xác định" },
                    { 186, 19, "Tổn thương bụng, lưng dưới, cột sống thắt lưng và chân hông" },
                    { 173, 18, "Các phát hiện bất thường về xét nghiệm các dịch cơ thể các chất và mô, không có chẩn đoán" },
                    { 175, 19, "Một vài biến chứng sớm của chấn thương" },
                    { 176, 19, "Tổn thương ở cổ tay và bàn tay" },
                    { 177, 19, "Di chứng của tổn thương, của nhiễm độc và của hậu quả khác của căn nguyên từ bên ngoài" },
                    { 178, 19, "Tổn thương tại háng và đùi" },
                    { 179, 19, "Tổn thương tác động nhiều vùng cơ thể" },
                    { 180, 19, "Tác động của vật lạ vào qua lỗ tự nhiên" },
                    { 181, 19, "Tổn thương tại khuỷu tay và cẳng tay" },
                    { 182, 19, "Bỏng và ăn mòn" },
                    { 183, 19, "Ngộ độc do thuốc, dược phẩm và chất sinh học" },
                    { 184, 19, "Tổn thương tại cổ chân và bàn chân" },
                    { 174, 18, "Triệu chứng và dấu hiệu liên quan tới hệ tiết niệu" },
                    { 110, 12, "Các bệnh da và tổ chức dưới da liên quan đến bức xạ" },
                    { 109, 12, "Các bệnh khác của da và tổ chức dưới da    " },
                    { 108, 12, "Nhiễm khuẩn da và mô dưới da" },
                    { 34, 4, "Các rối loạn khác về sự điều hoà glucose và bài tiết của tụy nội tiết" },
                    { 35, 4, "Bệnh tuyến giáp" },
                    { 36, 4, "Những bệnh thiếu dinh dưỡng khác" },
                    { 37, 4, "Rối loạn chuyển hoá" },
                    { 38, 4, "Rối loạn các tuyến nội tiết khác" },
                    { 39, 4, "Đái tháo đường" },
                    { 40, 4, "Béo phì và –tình trạng thừa dinh dưỡng khác" },
                    { 41, 5, "Rối loạn khí sắc [cảm xúc]" },
                    { 42, 5, "Các rối loạn bệnh tâm căn có liên quan đến stress và rối loạn dạng cơ thể" },
                    { 43, 5, "Tâm thần phân liệt, rối loạn loại phân liệt và các rối loạn hoang tưởng" },
                    { 33, 4, "Suy dinh dưỡng" },
                    { 44, 5, "Rối loạn tâm thần và hành vi do sử dụng chất tác động tâm thần" },
                    { 46, 5, "Các rối loạn về phát triển tâm lý" },
                    { 47, 5, "Hội chứng hành vi kết hợp với rối loạn sinh lý và nhân tố cơ thể" },
                    { 48, 5, "Các rối loạn hành vi và cảm xúc thường khởi phát ở tuổi trẻ em và thanh thiếu niên" },
                    { 49, 5, "Rối loạn tâm thần không biệt định" },
                    { 50, 5, "Rối loạn nhân cách và hành vi ở người trưởng thành" },
                    { 51, 5, "Rối loạn tâm thần thực tổn bao gồm rối loạn tâm thần triệu chứng" },
                    { 52, 6, "Bệnh mất myelin của hệ thần kinh trung ướng" },
                    { 53, 6, "Bệnh chu kỳ và kịch phát" },
                    { 54, 6, "Bệnh dây, rễ và đám rối thần kinh" },
                    { 55, 6, "Bệnh thoái hoá khác của hệ thần kinh" },
                    { 45, 5, "Chậm phát triển tâm thần" },
                    { 56, 6, "Bệnh viêm hệ thần kinh trung ương" },
                    { 32, 3, "Thiếu máu tan máu" },
                    { 30, 3, "Suy tuỷ xương và các bệnh thiếu máu khác" },
                    { 8, 1, "Bệnh lao" },
                    { 9, 1, "Bệnh do Rickettsia" },
                    { 10, 1, "Bệnh do xoắn trùng khác" },
                    { 11, 1, "Di chứng của bệnh nhiễm trùng và ký sinh trùng" },
                    { 12, 1, "Nhiễm virus ở hệ thần kinh trung ương" },
                    { 13, 1, "Bệnh chấy rận, bệnh ghẻ và nhiễm ký sinh trùng khác" },
                    { 14, 1, "Bệnh giun sán" },
                    { 15, 1, "Bệnh nhiễm trùng lây truyền chủ yếu qua đường tình dục" },
                    { 16, 1, "Các tác nhân vi khuẩn, virus và tác nhân gây nhiễm khuẩn khác" },
                    { 17, 1, "Bệnh nhiễm trùng đường ruột" },
                    { 31, 3, "U ác tính" },
                    { 18, 1, "Nhiễm virus có đặc điểm tổn thương tại da và niêm mạc" },
                    { 20, 1, "Bệnh do ký sinh trùng đơn bào" },
                    { 21, 1, "Bệnh nhiễm nấm" },
                    { 22, 2, "U lành" },
                    { 23, 2, "U tân sinh không chắc chắn hoặc không biết tính chất" },
                    { 24, 2, "U tân sinh tại chỗ" },
                    { 25, 2, "U ác được chẩn đoán xác định hay nghi ngờ là nguyên phát của các cơ quan xác định, ngoại trừ của mô bạch huyết, mô tạo huyết và mô liên" },
                    { 26, 2, "U ác tính" },
                    { 27, 3, "Bệnh thiếu máu dinh dưỡng" },
                    { 28, 3, "Các rối loạn đông máu, ban xuất huyết và tình trạng xuất huyết khác" },
                    { 29, 3, "Các bệnh khác của máu và cơ quan tạo máu" },
                    { 19, 1, "Bệnh nhiễm khuẩn khác" },
                    { 211, 22, "Mã tạm thời cho một số bệnh mới hoặc chưa rõ bệnh nguyên hoặc sử dụng trong cấp cứu" },
                    { 57, 6, "Các bệnh khác của hệ thần kinh" },
                    { 59, 6, "Bệnh của khớp thần kinh - cơ và cơ" },
                    { 86, 9, "Bệnh mạch máu não" },
                    { 87, 9, "Bệnh tim mạn tính do thấp" },
                    { 88, 10, "Nhiễm trùng đường hô hấp dưới cấp khác" },
                    { 89, 10, "Bệnh hô hấp dưới mạn tính" },
                    { 90, 10, "Cúm và viêm phổi" },
                    { 91, 10, "Các bệnh hô hấp khác ảnh hưởng chủ yếu đến mô kẽ" },
                    { 92, 10, "Các bệnh khác của đường hô hấp trên" },
                    { 93, 10, "Các bệnh lý khác của hệ hô hấp" },
                    { 94, 10, "Bệnh khác của màng phổi" },
                    { 95, 10, "Tình trạng nung mủ và hoại tử của đường hô hấp dưới" },
                    { 85, 9, "Rối loạn khác và không xác định của hệ tuần hoàn" },
                    { 96, 10, "Nhiễm trùng hô hấp trên cấp" },
                    { 98, 11, "Bệnh đường ruột khác" },
                    { 99, 11, "Bệnh túi mật, ống mật và tụy" },
                    { 100, 11, "Bệnh của gan" },
                    { 101, 11, "Bệnh của phúc mạc" },
                    { 102, 11, "Bệnh của thực quản, dạ dày và tá tràng" },
                    { 103, 11, "Thoát vị" },
                    { 104, 11, "Bệnh của khoang miệng, tuyến nước bọt và xương hàm" },
                    { 105, 11, "Bệnh khác của hệ tiêu hoá" },
                    { 106, 11, "Bệnh ruột thừa" },
                    { 107, 11, "Viêm ruột non và đại tràng không do nhiễm trùng" },
                    { 97, 10, "Các bệnh phổi do tác nhân bên ngoài" },
                    { 58, 6, "Viêm nhiều dây thần kinh và bệnh hệ thần kinh ngoại biên khác" },
                    { 84, 9, "Bệnh động mạch, tiểu động mạch và mao mạch" },
                    { 82, 9, "Bệnh tĩnh mạch, mạch bạch huyết và hạch bạch huyết không phân loại nơi khác" },
                    { 60, 6, "Bại não và những hội chứng liệt khác" },
                    { 61, 6, "Hội chứng ngoại tháp và rối loạn vận động" },
                    { 62, 6, "Bệnh teo hệ thống ảnh hưởng chủ yếu tới hệ thần kinh trung ương" },
                    { 63, 7, "Bệnh thủy tinh thể" },
                    { 64, 7, "Rối loạn thị giác và mù lòa" },
                    { 65, 7, "Bệnh dịch kính và nhãn cầu" },
                    { 66, 7, "Bệnh của kết mạc" },
                    { 67, 7, "Bệnh mắt và phần phụ" },
                    { 68, 7, "Bệnh glôcôm" },
                    { 69, 7, "Bệnh củng mạc, giác mạc, mống mắt và thể mi" },
                    { 83, 9, "Bệnh tim do phổi và bệnh tuần hoàn phổi" },
                    { 70, 7, "Bệnh cơ vận nhãn, vận nhãn hai mắt điều tiết và khúc xạ" },
                    { 72, 7, "Bệnh của mí mắt, lệ bộ và hốc mắt" },
                    { 73, 7, "Bệnh thần kinh thị và đường dẫn thị giác" },
                    { 74, 8, "Bệnh của tai ngoài" },
                    { 75, 8, "Bệnh của tai giữa và xương chũm" },
                    { 76, 8, "Bệnh khác của tai" },
                    { 77, 8, "Bệnh của tai trong" },
                    { 78, 9, "Thể bệnh tim khác" },
                    { 79, 9, "Bệnh tim thiếu máu cục bộ" },
                    { 80, 9, "Bệnh lý tăng huyết áp" },
                    { 81, 9, "Thấp khớp cấp" },
                    { 71, 7, "Bệnh hắc mạc và võng mạc" },
                    { 212, 22, "Kháng các thuốc kháng sinh và chống ung thư" }
                });

            migrationBuilder.InsertData(
                table: "Numbers",
                columns: new[] { "NumberId", "GroupId", "Name" },
                values: new object[,]
                {
                    { 1, 7, "Số TT 1" },
                    { 132, 137, "Số TT 15" },
                    { 133, 138, "Số TT 15" },
                    { 134, 139, "Số TT 15" },
                    { 135, 140, "Số TT 15" },
                    { 136, 141, "Số TT 15" },
                    { 137, 142, "Số TT 16" },
                    { 138, 143, "Số TT 16" },
                    { 139, 144, "Số TT 16" },
                    { 140, 144, "Số TT 16" },
                    { 141, 146, "Số TT 16" },
                    { 142, 147, "Số TT 16" },
                    { 143, 148, "Số TT 16" },
                    { 144, 149, "Số TT 16" },
                    { 145, 150, "Số TT 16" },
                    { 146, 151, "Số TT 17" },
                    { 147, 152, "Số TT 17" },
                    { 148, 153, "Số TT 17" },
                    { 149, 154, "Số TT 17" },
                    { 150, 155, "Số TT 17" },
                    { 151, 156, "Số TT 17" },
                    { 152, 157, "Số TT 17" },
                    { 131, 135, "Số TT 15" },
                    { 130, 135, "Số TT 15" },
                    { 129, 134, "Số TT 15" },
                    { 128, 132, "Số TT 14" },
                    { 106, 110, "Số TT 12 " },
                    { 107, 111, "Số TT 12 " },
                    { 108, 112, "Số TT 12 " },
                    { 109, 113, "Số TT 12 " },
                    { 110, 114, "Số TT 12 " },
                    { 111, 115, "Số TT 12 " },
                    { 112, 116, "Số TT 13" },
                    { 113, 117, "Số TT 13" },
                    { 114, 118, "Số TT 13" },
                    { 115, 119, "Số TT 13" },
                    { 153, 158, "Số TT 17" },
                    { 116, 120, "Số TT 13" },
                    { 118, 122, "Số TT 14" },
                    { 119, 123, "Số TT 14" },
                    { 120, 124, "Số TT 14" },
                    { 121, 125, "Số TT 14" },
                    { 122, 126, "Số TT 14" },
                    { 123, 127, "Số TT 14" },
                    { 124, 128, "Số TT 14" },
                    { 125, 129, "Số TT 14" },
                    { 126, 130, "Số TT 14" },
                    { 127, 131, "Số TT 14" },
                    { 117, 121, "Số TT 13" },
                    { 154, 159, "Số TT 17" },
                    { 155, 160, "Số TT 17" },
                    { 156, 161, "Số TT 17" },
                    { 183, 189, "Số TT 19" },
                    { 184, 190, "Số TT 19" },
                    { 185, 191, "Số TT 19" },
                    { 186, 191, "Số TT 19" },
                    { 187, 193, "Số TT 19" },
                    { 188, 194, "Số TT 19" },
                    { 189, 195, "Số TT 19" },
                    { 190, 196, "Số TT 20" },
                    { 191, 197, "Số TT 20" },
                    { 192, 198, "Số TT 20" },
                    { 182, 188, "Số TT 19" },
                    { 193, 199, "Số TT 20" },
                    { 195, 201, "Số TT 20" },
                    { 196, 202, "Số TT 20" },
                    { 197, 203, "Số TT 20" },
                    { 198, 204, "Số TT 21" },
                    { 199, 205, "Số TT 21" },
                    { 200, 206, "Số TT 21" },
                    { 201, 207, "Số TT 21" },
                    { 202, 208, "Số TT 21" },
                    { 203, 209, "Số TT 21" },
                    { 204, 210, "Số TT 21" },
                    { 194, 200, "Số TT 20" },
                    { 105, 109, "Số TT 12 " },
                    { 181, 187, "Số TT 19" },
                    { 179, 185, "Số TT 19" },
                    { 157, 162, "Số TT 18" },
                    { 158, 163, "Số TT 18" },
                    { 159, 164, "Số TT 18" },
                    { 160, 165, "Số TT 18" },
                    { 161, 166, "Số TT 18" },
                    { 162, 167, "Số TT 18" },
                    { 163, 168, "Số TT 18" },
                    { 164, 169, "Số TT 18" },
                    { 165, 170, "Số TT 18" },
                    { 166, 171, "Số TT 18" },
                    { 180, 186, "Số TT 19" },
                    { 167, 172, "Số TT 18" },
                    { 169, 174, "Số TT 18" },
                    { 170, 175, "Số TT 19" },
                    { 171, 176, "Số TT 19" },
                    { 172, 178, "Số TT 19" },
                    { 173, 179, "Số TT 19" },
                    { 174, 180, "Số TT 19" },
                    { 175, 181, "Số TT 19" },
                    { 176, 182, "Số TT 19" },
                    { 177, 183, "Số TT 19" },
                    { 178, 184, "Số TT 19" },
                    { 168, 173, "Số TT 18" },
                    { 104, 108, "Số TT 12 " },
                    { 103, 107, "Số TT 11" },
                    { 102, 106, "Số TT 11" },
                    { 28, 33, "Số TT 4" },
                    { 29, 34, "Số TT 4" },
                    { 30, 35, "Số TT 4" },
                    { 31, 36, "Số TT 4" },
                    { 32, 37, "Số TT 4" },
                    { 33, 38, "Số TT 4" },
                    { 34, 39, "Số TT 4" },
                    { 35, 40, "Số TT 4" },
                    { 36, 41, "Số TT 1" },
                    { 37, 41, "Số TT 5" },
                    { 27, 33, "Số TT 1" },
                    { 38, 42, "Số TT 5" },
                    { 40, 44, "Số TT 5" },
                    { 41, 45, "Số TT 5" },
                    { 42, 46, "Số TT 5" },
                    { 43, 47, "Số TT 5" },
                    { 44, 48, "Số TT 5" },
                    { 45, 49, "Số TT 5" },
                    { 46, 50, "Số TT 5" },
                    { 47, 51, "Số TT 5" },
                    { 48, 52, "Số TT 6" },
                    { 49, 53, "Số TT 6" },
                    { 39, 43, "Số TT 5" },
                    { 50, 54, "Số TT 6" },
                    { 26, 32, "Số TT 3" },
                    { 24, 30, "Số TT 3" },
                    { 2, 8, "Số TT 1" },
                    { 3, 9, "Số TT 1" },
                    { 4, 10, "Số TT 1" },
                    { 5, 11, "Số TT 1" },
                    { 6, 12, "Số TT 1" },
                    { 7, 13, "Số TT 1" },
                    { 8, 14, "Số TT 1" },
                    { 9, 15, "Số TT 1" },
                    { 10, 16, "Số TT 1" },
                    { 11, 17, "Số TT 1" },
                    { 25, 31, "Số TT 3" },
                    { 12, 18, "Số TT 1" },
                    { 14, 20, "Số TT 1" },
                    { 15, 21, "Số TT 1" },
                    { 16, 22, "Số TT 2" },
                    { 17, 23, "Số TT 2" },
                    { 18, 24, "Số TT 2" },
                    { 19, 25, "Số TT 2" },
                    { 20, 26, "Số TT 2" },
                    { 21, 27, "Số TT 3" },
                    { 22, 28, "Số TT 3" },
                    { 23, 29, "Số TT 3" },
                    { 13, 19, "Số TT 1" },
                    { 205, 211, "Số TT 22" },
                    { 51, 55, "Số TT 6" },
                    { 53, 57, "Số TT 6" },
                    { 80, 84, "Số TT 9" },
                    { 81, 85, "Số TT 9" },
                    { 82, 86, "Số TT 9" },
                    { 83, 87, "Số TT 9" },
                    { 84, 88, "Số TT 10" },
                    { 85, 89, "Số TT 10" },
                    { 86, 90, "Số TT 10" },
                    { 87, 91, "Số TT 10" },
                    { 88, 92, "Số TT 10" },
                    { 89, 93, "Số TT 10" },
                    { 79, 83, "Số TT 9" },
                    { 90, 94, "Số TT 10" },
                    { 92, 96, "Số TT 10" },
                    { 93, 97, "Số TT 10" },
                    { 94, 98, "Số TT 11" },
                    { 95, 99, "Số TT 11" },
                    { 96, 100, "Số TT 11" },
                    { 97, 101, "Số TT 11" },
                    { 98, 102, "Số TT 11" },
                    { 99, 103, "Số TT 11" },
                    { 100, 104, "Số TT 11" },
                    { 101, 105, "Số TT 11" },
                    { 91, 95, "Số TT 10" },
                    { 52, 56, "Số TT 6" },
                    { 78, 82, "Số TT 9" },
                    { 76, 80, "Số TT 9" },
                    { 54, 58, "Số TT 6" },
                    { 55, 59, "Số TT 6" },
                    { 56, 60, "Số TT 6" },
                    { 57, 61, "Số TT 6" },
                    { 58, 62, "Số TT 6" },
                    { 59, 63, "Số TT 7" },
                    { 60, 64, "Số TT 7" },
                    { 61, 65, "Số TT 7" },
                    { 62, 66, "Số TT 7" },
                    { 63, 67, "Số TT 7" },
                    { 77, 81, "Số TT 9" },
                    { 64, 68, "Số TT 7" },
                    { 66, 70, "Số TT 7" },
                    { 67, 71, "Số TT 7" },
                    { 68, 72, "Số TT 7" },
                    { 69, 73, "Số TT 7" },
                    { 70, 74, "Số TT 8" },
                    { 71, 75, "Số TT 8" },
                    { 72, 76, "Số TT 8" },
                    { 73, 77, "Số TT 8" },
                    { 74, 78, "Số TT 9" },
                    { 75, 79, "Số TT 9" },
                    { 65, 69, "Số TT 7" },
                    { 206, 212, "Số TT 22" }
                });

            migrationBuilder.InsertData(
                table: "Diseases",
                columns: new[] { "DiseaseId", "EnglishName", "NumberId", "Symptom", "VietnameseName" },
                values: new object[,]
                {
                    { 1, "Acute hepatitis A", 1, "Đang chờ cập nhập!", "Viêm gan A cấp" },
                    { 55, "Foodborne Clostridium perfringens [Clostridium welchii] intoxication", 11, "Đang chờ cập nhập!", "Nhiễm độc thức ăn do độc tố của Clostridium perfringens [Clostridium welchii]" },
                    { 54, "Campylobacter enteritis", 11, "Đang chờ cập nhập!", "Viêm ruột do Campylobacter" },
                    { 53, "Enterohaemorrhagic Escherichia coli infection", 11, "Đang chờ cập nhập!", "Nhiễm Escherichia coli gây xuất huyết đường ruột" },
                    { 52, "Cholera", 11, "Đang chờ cập nhập!", "Bệnh tả" },
                    { 51, "Proteus (mirabilis)(morganii) as the cause of diseases classified to other chapters", 10, "Đang chờ cập nhập!", "Proteus (mirabilis)(morganii) gây các bệnh đã được phân loại ở chương khác" },
                    { 50, "Streptococcus, group D, as the cause of diseases classified to other chapters", 10, "Đang chờ cập nhập!", "Liên cầu, nhóm D, là nguyên nhân gây các bệnh phân loại ở chương khác" },
                    { 49, "Liên cầu, nhóm B, là nguyên nhân gây các bệnh phân loại ở chương khác", 10, "Đang chờ cập nhập!", "Streptococcus, group B, as the cause of diseases classified to other chapters" },
                    { 48, "Streptococcus, group A, as the cause of diseases classified to other chapters", 10, "Đang chờ cập nhập!", "Liên cầu, nhóm A, là nguyên nhân gây các bệnh phân loại ở chương khác" },
                    { 47, "Streptococcus and staphylococcus as the cause of diseases classified to other chapters", 10, "Đang chờ cập nhập!", "Liên cầu và tụ cầu là nguyên nhân gây bệnh, được phân loại ở các chương khác" },
                    { 46, "Other symptomatic late syphilis", 9, "Đang chờ cập nhập!", "Giang mai muộn khác có triệu chứng" },
                    { 45, "Other secondary syphilis", 9, "Đang chờ cập nhập!", "Giang mai thứ phát khác" },
                    { 44, "Early syphilis", 9, "Đang chờ cập nhập!", "Giang mai sớm" },
                    { 43, "Early congenital syphilis, unspecified", 9, "Đang chờ cập nhập!", "Giang mai bẩm sinh sớm, không đặc hiệu" },
                    { 42, "Congenital syphilis", 9, "Đang chờ cập nhập!", "Giang mai bẩm sinh" },
                    { 41, "Taeniasis", 8, "Đang chờ cập nhập!", "Bệnh sán dây  " },
                    { 56, "Other specified bacterial foodborne intoxications", 11, "Đang chờ cập nhập!", "Nhiễm độc thức ăn do độc tố của vi khuẩn xác định khác" },
                    { 40, "Fasciolopsiasis", 8, "Đang chờ cập nhập!", "Bệnh do Fasciolopsis" },
                    { 57, "Herpesviral [herpes simplex] infections", 12, "Đang chờ cập nhập!", "Bệnh do Herpes simplex" },
                    { 59, "Zoster [herpes zoster]", 12, "Đang chờ cập nhập!", "Bệnh do herpes zoster" },
                    { 74, "White piedra", 15, "Đang chờ cập nhập!", "Bệnh nấm do Trichosporum cuteneum (râu, lông)" },
                    { 73, "Dermatophytosis, unspecified", 15, "Đang chờ cập nhập!", "Bệnh nấm da, không đặc hiệu" },
                    { 72, "Tinea barbae and tinea capitis", 15, "Đang chờ cập nhập!", "Bệnh nấm ở cằm và nấm da đầu" },
                    { 71, "Chagas disease (chronic) with other organ involvement", 14, "Đang chờ cập nhập!", "Bệnh Chagas (mạn tính) ảnh hưởng đến cơ quan khác" },
                    { 70, "African trypanosomiasis, unspecified", 14, "Đang chờ cập nhập!", "Bệnh do trypanosoma châu Phi, không đặc hiệu" },
                    { 69, "Other parasitologically confirmed malaria, not elsewhere classified", 14, "Đang chờ cập nhập!", "Sốt rét khác xác nhận bằng ký sinh trùng học, chưa được phân loại" },
                    { 68, "Plasmodium vivax malaria with other complications", 14, "Đang chờ cập nhập!", "Sốt rét Plasmodium vivax với biến chứng khác" },
                    { 67, "Other severe and complicated Plasmodium falciparum malaria", 14, "Đang chờ cập nhập!", "Sốt rét Plasmodium falciparum thể nặng và biến chứng khác" },
                    { 66, "Nasopharyngeal diphtheria", 13, "Đang chờ cập nhập!", "Bệnh bạch hầu thể mũi - họng" },
                    { 65, "Listerial meningitis and meningoencephalitis", 13, "Đang chờ cập nhập!", "Viêm màng não và viêm não màng não do listeria" },
                    { 64, "Mycobacterial infection, unspecified", 13, "Đang chờ cập nhập!", "Nhiễm khuẩn mycobacteria không đặc hiệu" },
                    { 63, "Borderline tuberculoid leprosy", 13, "Đang chờ cập nhập!", "Bệnh phong thể củ ranh giới" },
                    { 62, "Leprosy [Hansen s disease]", 13, "Đang chờ cập nhập!", "Bệnh phong (bệnh Hansen)" },
                    { 61, "Measles with intestinal complications", 12, "Đang chờ cập nhập!", "Sởi với biến chứng ở ruột" },
                    { 60, "Measles complicated by meningitisG02.0", 12, "Đang chờ cập nhập!", "Sởi biến chứng viêm màng não G02.0" },
                    { 58, "Herpesviral infection, unspecified", 12, "Đang chờ cập nhập!", "Nhiễm Virus Herpes, không đặc hiệu" },
                    { 39, "Other specified fluke infections", 8, "Đang chờ cập nhập!", "Nhiễm sán lá xác định khác" },
                    { 38, "Fascioliasis", 8, "Đang chờ cập nhập!", "Bệnh Fasciola" },
                    { 37, "Cercarial dermatitis", 8, "Đang chờ cập nhập!", "Viêm da do ấu trùng" },
                    { 16, "Nonvenereal syphilis", 4, "Đang chờ cập nhập!", "Giang mai không lây qua đường tình dục" },
                    { 15, "Trench fever", 3, "Đang chờ cập nhập!", "Sốt chiến hào" },
                    { 14, "Q fever", 3, "Đang chờ cập nhập!", "Sốt Q" },
                    { 13, "Other spotted fevers", 3, "Đang chờ cập nhập!", "Sốt phát ban dạng đốm khác" },
                    { 12, "Typhus fever due to Rickettsia typhi", 3, "Đang chờ cập nhập!", "Sốt phát ban do Rickettsia typhi" },
                    { 11, "Typhus fever", 3, "Đang chờ cập nhập!", "Bệnh sốt phát ban do Rickettsia" },
                    { 10, "Primary respiratory tuberculosis without mention of bacteriological or histological confirmation", 2, "Đang chờ cập nhập!", "Lao hô hấp sơ nhiễm không đề cập đến việc xác nhận về vi khuẩn học và mô học" },
                    { 9, "Respiratory tuberculosis unspecified, confirmed bacteriologically and histologically", 2, "Đang chờ cập nhập!", "Lao hô hấp không xác định, xác nhận về vi trùng học và mô học" },
                    { 8, "Tuberculous pleurisy, confirmed bacteriologically and histologically", 2, "Đang chờ cập nhập!", "Lao màng phổi, xác nhận về vi trùng học và mô học" },
                    { 7, "Tuberculosis of intrathoracic lymph nodes, confirmed bacteriologically and histologically", 2, "Đang chờ cập nhập!", "Lao hạch lympho trong lồng ngực, xác nhận về vi trùng học hoặc mô học" },
                    { 6, "Respiratory tuberculosis, bacteriologically and histologically confirmed", 2, "Đang chờ cập nhập!", "Lao hô hấp, có xác nhận về vi khuẩn học và mô học" },
                    { 5, "Chronic viral hepatitis", 1, "Đang chờ cập nhập!", "Viêm gan virus mạn" },
                    { 4, "Acute delta-(super)infection of hepatitis B carrier", 1, "Đang chờ cập nhập!", "Viêm gan D cấp tính bội nhiễm trên người mang viêm gan B" },
                    { 3, "Acute hepatitis B", 1, "Đang chờ cập nhập!", "Viêm gan B cấp" },
                    { 2, "Hepatitis A with hepatic coma", 1, "Đang chờ cập nhập!", "Viêm gan A có hôn mê gan" },
                    { 17, "Yaws", 4, "Đang chờ cập nhập!", "Ghẻ cóc (do nhiễm Treponema pertenue)" },
                    { 18, "Other manifestations of yaws", 4, "Đang chờ cập nhập!", "Biểu hiện khác của ghẻ cóc" },
                    { 19, "Primary lesions of pinta", 4, "Đang chờ cập nhập!", "Tổn thương tiên phát của pinta" },
                    { 20, "Other spirochaetal infections", 4, "Đang chờ cập nhập!", "Bệnh do xoắn trùng khác" },
                    { 36, "Schistosomiasis [bilharziasis]", 8, "Đang chờ cập nhập!", "Bệnh sán máng [bilharziasis]" },
                    { 35, "Other acariasis", 7, "Đang chờ cập nhập!", "Các bệnh do ve khác" },
                    { 34, "Nasopharyngeal myiasis", 7, "Đang chờ cập nhập!", "Bệnh giòi ở mũi họng" },
                    { 33, "Scabies", 7, "Đang chờ cập nhập!", "Bệnh ngứa do ghẻ" },
                    { 32, "Pediculosis due to Pediculus humanus capitis", 7, "Đang chờ cập nhập!", "Bệnh chấy rận do Pediculus humanus capitis" },
                    { 31, "Pediculosis and phthiriasis", 7, "Đang chờ cập nhập!", "Bệnh chấy rận" },
                    { 30, "Other mosquito-borne viral encephalitis", 6, "Đang chờ cập nhập!", "Viêm não virus khác do muỗi truyền" },
                    { 75, "Candidiasis, unspecified", 15, "Đang chờ cập nhập!", "Nhiễm candida không xác định" },
                    { 29, "Rabies", 6, "Đang chờ cập nhập!", "Bệnh dại" },
                    { 27, "Acute paralytic poliomyelitis, wild virus, indigenous", 6, "Đang chờ cập nhập!", "Bệnh bại liệt cấp, thể liệt, virus hoang dại, nội địa" },
                    { 26, "Acute poliomyelitis", 6, "Đang chờ cập nhập!", "Bệnh bại liệt cấp" },
                    { 25, "Sequelae of trachoma", 5, "Đang chờ cập nhập!", "Di chứng bệnh mắt hột" },
                    { 24, "Sequelae of viral hepatitis", 5, "Đang chờ cập nhập!", "Di chứng viêm gan virus" },
                    { 23, "Sequelae of tuberculosis of other organs", 5, "Đang chờ cập nhập!", "Di chứng do lao cơ quan khác" },
                    { 22, "Sequelae of genitourinary tuberculosis", 5, "Đang chờ cập nhập!", "Di chứng do lao tiết niệu - sinh dục" },
                    { 21, "Sequelae of tuberculosis", 5, "Đang chờ cập nhập!", "Di chứng do lao" },
                    { 28, "Atypical virus infections of central nervous system", 6, "Đang chờ cập nhập!", "Bệnh do virus không điển hình ở hệ thần kinh trung ương" },
                    { 76, "Chronic pulmonary coccidioidomycosis", 15, "Đang chờ cập nhập!", "Nhiễm nấm coccidioides ở phổi mạn tính" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Diseases_NumberId",
                table: "Diseases",
                column: "NumberId");

            migrationBuilder.CreateIndex(
                name: "IX_Diseases_Users_UserId",
                table: "Diseases_Users",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Groups_ChapterId",
                table: "Groups",
                column: "ChapterId");

            migrationBuilder.CreateIndex(
                name: "IX_Numbers_GroupId",
                table: "Numbers",
                column: "GroupId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Diseases_Users");

            migrationBuilder.DropTable(
                name: "Diseases");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "Numbers");

            migrationBuilder.DropTable(
                name: "Groups");

            migrationBuilder.DropTable(
                name: "Chapters");
        }
    }
}
